<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entities\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'version', '' . "\0" . 'App\\Entities\\User' . "\0" . 'id', '' . "\0" . 'App\\Entities\\User' . "\0" . 'username', '' . "\0" . 'App\\Entities\\User' . "\0" . 'firstName', '' . "\0" . 'App\\Entities\\User' . "\0" . 'lastName', '' . "\0" . 'App\\Entities\\User' . "\0" . 'password', '' . "\0" . 'App\\Entities\\User' . "\0" . 'active', '' . "\0" . 'App\\Entities\\User' . "\0" . 'activeHash', '' . "\0" . 'App\\Entities\\User' . "\0" . 'recoverHash', '' . "\0" . 'App\\Entities\\User' . "\0" . 'createdAt', '' . "\0" . 'App\\Entities\\User' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entities\\User' . "\0" . 'modifiedBy', '' . "\0" . 'App\\Entities\\User' . "\0" . 'email', '' . "\0" . 'App\\Entities\\User' . "\0" . 'token', '' . "\0" . 'App\\Entities\\User' . "\0" . 'tokenExpire', '' . "\0" . 'App\\Entities\\User' . "\0" . 'portalsModified', '' . "\0" . 'App\\Entities\\User' . "\0" . 'portalsDeactivated', '' . "\0" . 'App\\Entities\\User' . "\0" . 'portalsCreated', '' . "\0" . 'App\\Entities\\User' . "\0" . 'createdBy'];
        }

        return ['__isInitialized__', 'version', '' . "\0" . 'App\\Entities\\User' . "\0" . 'id', '' . "\0" . 'App\\Entities\\User' . "\0" . 'username', '' . "\0" . 'App\\Entities\\User' . "\0" . 'firstName', '' . "\0" . 'App\\Entities\\User' . "\0" . 'lastName', '' . "\0" . 'App\\Entities\\User' . "\0" . 'password', '' . "\0" . 'App\\Entities\\User' . "\0" . 'active', '' . "\0" . 'App\\Entities\\User' . "\0" . 'activeHash', '' . "\0" . 'App\\Entities\\User' . "\0" . 'recoverHash', '' . "\0" . 'App\\Entities\\User' . "\0" . 'createdAt', '' . "\0" . 'App\\Entities\\User' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entities\\User' . "\0" . 'modifiedBy', '' . "\0" . 'App\\Entities\\User' . "\0" . 'email', '' . "\0" . 'App\\Entities\\User' . "\0" . 'token', '' . "\0" . 'App\\Entities\\User' . "\0" . 'tokenExpire', '' . "\0" . 'App\\Entities\\User' . "\0" . 'portalsModified', '' . "\0" . 'App\\Entities\\User' . "\0" . 'portalsDeactivated', '' . "\0" . 'App\\Entities\\User' . "\0" . 'portalsCreated', '' . "\0" . 'App\\Entities\\User' . "\0" . 'createdBy'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getVersion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVersion', []);

        return parent::getVersion();
    }

    /**
     * {@inheritDoc}
     */
    public function setVersion($incVersion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVersion', [$incVersion]);

        return parent::setVersion($incVersion);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($hashedPassword)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$hashedPassword]);

        return parent::setPassword($hashedPassword);
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstName($firstName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstName', [$firstName]);

        return parent::setFirstName($firstName);
    }

    /**
     * {@inheritDoc}
     */
    public function setLastName($lastName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastName', [$lastName]);

        return parent::setLastName($lastName);
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($now)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$now]);

        return parent::setCreatedAt($now);
    }

    /**
     * {@inheritDoc}
     */
    public function GetId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'GetId', []);

        return parent::GetId();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive($int)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', [$int]);

        return parent::setActive($int);
    }

    /**
     * {@inheritDoc}
     */
    public function setUserName($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserName', [$email]);

        return parent::setUserName($email);
    }

    /**
     * {@inheritDoc}
     */
    public function assignDeactivatedPortals(\App\Entities\Portal $incDeactivatedPortal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'assignDeactivatedPortals', [$incDeactivatedPortal]);

        return parent::assignDeactivatedPortals($incDeactivatedPortal);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeactivatedPortals()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeactivatedPortals', []);

        return parent::getDeactivatedPortals();
    }

    /**
     * {@inheritDoc}
     */
    public function assignModifiedPortals(\App\Entities\Portal $incModifiedPortal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'assignModifiedPortals', [$incModifiedPortal]);

        return parent::assignModifiedPortals($incModifiedPortal);
    }

    /**
     * {@inheritDoc}
     */
    public function getModifiedPortals()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifiedPortals', []);

        return parent::getModifiedPortals();
    }

    /**
     * {@inheritDoc}
     */
    public function setToken($incToken)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setToken', [$incToken]);

        return parent::setToken($incToken);
    }

    /**
     * {@inheritDoc}
     */
    public function setTokenExpire($incTokenExpire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTokenExpire', [$incTokenExpire]);

        return parent::setTokenExpire($incTokenExpire);
    }

    /**
     * {@inheritDoc}
     */
    public function setActiveHash($incActiveHash)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActiveHash', [$incActiveHash]);

        return parent::setActiveHash($incActiveHash);
    }

    /**
     * {@inheritDoc}
     */
    public function setRecoverHash($incRecoverHash)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecoverHash', [$incRecoverHash]);

        return parent::setRecoverHash($incRecoverHash);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', []);

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy(\App\Entities\User $incCreatedBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', [$incCreatedBy]);

        return parent::setCreatedBy($incCreatedBy);
    }

}
